### ISSUE TITLE
Selecting elements of human prims should reference their human

### ISSUE THREAD

**Issue by Fruity-Grebbles** [cadop/HumanGenerator#71]
Eg. selecting a human's mesh should allow a user to modify the corresponding human

**Comment by Fruity-Grebbles** [comment]
@cadop Do we actually want this behavior?

**Comment by cadop** [comment]
Yes, prim hierarchy should be respected. If a hat is deleted, it should propagate. selecting a prim is because selecting a character in the scene won't select the main prim but instead a sub-prim. having users click back and forth is unncessary. If they click the hat in the scene, the human generator should recognize which human it is
